### ISSUE TITLE
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager' in conda environment with python3.6

### ISSUE THREAD

**Issue by falcorocks** [facebook/pyre-check#375]
I'm trying to use pyre-check within conda environments. I am having bad luck with python3.6 environments. Things work fine with python3.8 and later though.
Docs says pyre-check works on python3.6 and later. Wrong docs or bug?

Steps to reproduce & error message:
```bash
$ conda create -n test36 python=3.6
(...)
$ conda activate test36
$ pip install pyre-check #0.0.59
(...)
$ pyre init
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/test36/bin/pyre", line 5, in <module>
    from pyre_check.client.pyre import main
  File "/usr/local/Caskroom/miniconda/base/envs/test36/lib/python3.6/site-packages/pyre_check/client/pyre.py", line 30, in <module>
    from .commands import Command, ExitCode, v2
  File "/usr/local/Caskroom/miniconda/base/envs/test36/lib/python3.6/site-packages/pyre_check/client/commands/v2/__init__.py", line 6, in <module>
    from . import incremental  # noqa F401
  File "/usr/local/Caskroom/miniconda/base/envs/test36/lib/python3.6/site-packages/pyre_check/client/commands/v2/incremental.py", line 18, in <module>
    from . import server_connection, start
  File "/usr/local/Caskroom/miniconda/base/envs/test36/lib/python3.6/site-packages/pyre_check/client/commands/v2/start.py", line 37, in <module>
    from . import server_connection, server_event
  File "/usr/local/Caskroom/miniconda/base/envs/test36/lib/python3.6/site-packages/pyre_check/client/commands/v2/server_event.py", line 11, in <module>
    from . import async_server_connection
  File "/usr/local/Caskroom/miniconda/base/envs/test36/lib/python3.6/site-packages/pyre_check/client/commands/v2/async_server_connection.py", line 226, in <module>
    @contextlib.asynccontextmanager
AttributeError: module 'contextlib' has no attribute 'asynccontextmanager'
```

Update:
If I pin installation to 0.0.58, pyre works.

```bash
$ pyre --version
Binary version: 857747d8246cde76501481378a6b7cf2e7072a2c
Client version: internal-dev
$ pyre init
(...works...)
```

**Comment by MaggieMoss** [comment]
Looks like the linked commit above should fix the issue. Closing.

**Comment by falcorocks** [comment]
Thanks! Great work and great tool guys!
